// NORMAL KEYS

#define GC_BCKSPC	0x08
#define GC_TAB		0x09
#define GC_ENTER	0x0D
#define GC_ESC		0x1B


// SPECIAL KEYS

#define GC_UP		0x48
#define GC_DOWN		0x50
#define GC_LEFT		0x4B
#define GC_RIGHT	0x4D
#define GC_CANC		0x53
#define GC_HOME		0x47
#define GC_END		0x4F
#define GC_PGUP		0x49
#define GC_PGDOWN	0x51
#define GC_INS		0x52
#define GC_ALT_INS	-94
#define GC_ALT_A	0x1E
#define GC_ALT_B	0x30
#define GC_ALT_C	0x2E

#define GC_ALT_D	32
#define GC_ALT_E	18
#define GC_ALT_F	33
#define GC_ALT_G	34
#define GC_ALT_H	35
#define GC_ALT_I	23
#define GC_ALT_J	36
#define GC_ALT_K	37
#define GC_ALT_L	38
#define GC_ALT_M	50
#define GC_ALT_N	49
#define GC_ALT_O	24
#define GC_ALT_P	25
#define GC_ALT_Q	16
#define GC_ALT_R	19
#define GC_ALT_S	31
#define GC_ALT_T	20
#define GC_ALT_U	22
#define GC_ALT_V	47
#define GC_ALT_W	17
#define GC_ALT_X	45
#define GC_ALT_Y	21
#define GC_ALT_Z	44

#define GC_F1		59
#define GC_F2		60
#define GC_F3		61
#define GC_F4		62
#define GC_F5		63
#define GC_F6		64
#define GC_F7		65
#define GC_F8		66
#define GC_F9		67
#define GC_F10		68
#define GC_F11		-123
#define GC_F12		-122